#!/usr/bin/env python3
import os
import subprocess

import click
import waitress

try:
    from rogue_sky.api import app
except ImportError:
    print("Try installing the package `python setup.py install`")
    raise


@click.command()
@click.option("--dev", is_flag=True, help="Run the Flask development server.")
def start(dev):
    if dev:
        env = os.environ.copy()
        env["FLASK_APP"] = "rogue_sky/api.py"

        print("Starting development server...")
        subprocess.run(["flask", "run"], env=env)

    else:
        waitress.serve(app, host="127.0.0.1", port=8000)


if __name__ == "__main__":
    start()
